export const pathTitles = {
'activities/camping/campground-notes':``,
'activities/camping/food-ideas':``,
'activities/camping/fun-ideas':``,
'activities/camping/gear-checklist':``,
'activities/camping/sample_trip_a':``,
'asking-ai/crafty/how-do-you-make-t-shirt-yarn/bard':`what Bard said`,
'asking-ai/crafty/how-do-you-make-t-shirt-yarn/bing':`what Bing said`,
'asking-ai/crafty/how-do-you-make-t-shirt-yarn/chatgpt':`what ChatGPT said`,
'asking-ai/technical/list-files-from-a-terminal/bing':`what Bing said`,
'asking-ai/technical/most-common-term-for-writing-computer-code/bard':`what Bard said`,
'asking-ai/technical/most-common-term-for-writing-computer-code/bing':`what Bing said`,
'asking-ai/technical/most-common-term-for-writing-computer-code/chatgpt':`what ChatGPT said`,
'asking-ai/technical/no-cost-website-hosts/bard':``,
'asking-ai/technical/no-cost-website-hosts/bing':``,
'asking-ai/technical/no-cost-website-hosts/chatgpt':``,
'asking-ai/technical/shell-scripting/bash/list-git-repo-files-with-commit-date/bard':``,
'asking-ai/technical/shell-scripting/bash/list-git-repo-files-with-commit-date/bing':``,
'asking-ai/technical/shell-scripting/bash/list-git-repo-files-with-commit-date/chatgpt':``,
'asking-ai/technical/sitemap-file-format-preferred-by-search-engines/bard':`what Bard said`,
'asking-ai/technical/sitemap-file-format-preferred-by-search-engines/bing':`what Bing said`,
'asking-ai/technical/sitemap-file-format-preferred-by-search-engines/chatgpt':`what ChatGPT said`,
'blogs/kristy/2024/01/20/finding-new-recipes-to-try':``,
'blogs/kristy/2024/01/x/18-asking-ai':``,
'blogs/kristy/2024/01/x/19-asking-ai':``,
'coding/frameworks/bootstrap/cheatsheet-v5.3':``,
'coding/languages/markdown/markdown-cheat-sheet':``,
'coding/web-design/hamburger':`Hamburger Menus`,
'coding/web-design/sitemaps':`Sitemaps`,
'recipes/desserts/almond-cake':`Almond cake`,
'recipes/desserts/date-balls':`Date Balls`,
'recipes/desserts/ginger-snaps':`Ginger snaps`,
'recipes/desserts/rainbow-cookies':`Rainbow Cookies`,
'recipes/desserts/tiramisu':`Tiramisu`,
'recipes/meats/chicken-meatballs':`Chicken meatballs`,
'recipes/sides/macaroni-and-cheese-1-pot-version':`One-Pot Macaroni and Cheese Recipe`,
'recipes/sides/mashed-potatoes':`Mashed potatoes`,
'recipes/sides/yeast-rolls':`Yeast Rolls`,
'recipes/want-to-try/beef-stew/beef-stew-20240120-bard':``,
'recipes/want-to-try/beef-stew/beef-stew-20240120-bing':``,
'recipes/want-to-try/beef-stew/beef-stew-20240120-chatgpt':``,
'recipes/want-to-try/crab-cakes/crab-cakes-20240120-bard':``,
'recipes/want-to-try/crab-cakes/crab-cakes-20240120-bing':``,
'recipes/want-to-try/crab-cakes/crab-cakes-20240120-chatgpt':``,
'recipes':`Recipes`,
'sitemap':`Sitemap`,
'upcycling/food-scraps/coffee-grounds':`Reusing Coffee Grounds`,
'upcycling/food-scraps/tea-bags':`Reusing Tea Bags`,
'upcycling/textiles/t-shirts':`Upcycling T-shirts`,
}
