export const pathTitles = {
'activities/camping/campground-notes':`Campground Notes`,
'activities/camping/food-ideas':`Food Ideas`,
'activities/camping/fun-ideas':`Fun ideas`,
'activities/camping/gear-checklist':`Gear Checklist`,
'activities/camping/sample-trip':`Sample Trip`,
'asking-ai/crafty/how-do-you-make-t-shirt-yarn/bard':`what Bard said`,
'asking-ai/crafty/how-do-you-make-t-shirt-yarn/bing':`what Bing said`,
'asking-ai/crafty/how-do-you-make-t-shirt-yarn/chatgpt':`what ChatGPT said`,
'asking-ai/crafty/how-do-you-make-t-shirt-yarn':`How do you make t-shirt yarn?`,
'asking-ai/technical/list-files-from-a-terminal/bing':`what Bing said`,
'asking-ai/technical/list-files-from-a-terminal':`How do you list files from a terminal?`,
'asking-ai/technical/most-common-term-for-writing-computer-code/bard':`what Bard said`,
'asking-ai/technical/most-common-term-for-writing-computer-code/bing':`what Bing said`,
'asking-ai/technical/most-common-term-for-writing-computer-code/chatgpt':`what ChatGPT said`,
'asking-ai/technical/most-common-term-for-writing-computer-code':`What is the most common term for writing computer code?`,
'asking-ai/technical/no-cost-website-hosts/bard':``,
'asking-ai/technical/no-cost-website-hosts/bing':``,
'asking-ai/technical/no-cost-website-hosts/chatgpt':``,
'asking-ai/technical/no-cost-website-hosts':`Please list 10 places to host a website for free`,
'asking-ai/technical/shell-scripting/bash/list-git-repo-files-with-commit-date/bard':``,
'asking-ai/technical/shell-scripting/bash/list-git-repo-files-with-commit-date/bing':``,
'asking-ai/technical/shell-scripting/bash/list-git-repo-files-with-commit-date/chatgpt':``,
'asking-ai/technical/shell-scripting/bash/list-git-repo-files-with-commit-date':`Please write a bash script to list all the files in a local clone of a git repository with their last commit date`,
'asking-ai/technical/sitemap-file-format-preferred-by-search-engines/bard':`what Bard said`,
'asking-ai/technical/sitemap-file-format-preferred-by-search-engines/bing':`what Bing said`,
'asking-ai/technical/sitemap-file-format-preferred-by-search-engines/chatgpt':`what ChatGPT said`,
'asking-ai/technical/sitemap-file-format-preferred-by-search-engines':`I need to know the file format for the sitemap file that each search engine prefers`,
'asking-ai/technical/trim-file-leading-trailing-whitespace/bard':`what Bard said`,
'asking-ai/technical/trim-file-leading-trailing-whitespace/bing':`what Bing said`,
'asking-ai/technical/trim-file-leading-trailing-whitespace/chatgpt':`what ChatGPT said`,
'asking-ai/technical/trim-file-leading-trailing-whitespace':`In bash, how do I trim the contents of a file of leading and trailing whitespace and then write it back?`,
'blogs/kristy/2024/01/20/finding-new-recipes-to-try':``,
'blogs/kristy/2024/01/x/18-asking-ai':``,
'blogs/kristy/2024/01/x/19-asking-ai':``,
'coding/frameworks/bootstrap/cheatsheet-v5.3':``,
'coding/languages/markdown/markdown-cheat-sheet':``,
'coding/web-design/hamburger':`Hamburger Menus`,
'coding/web-design/sitemaps':`Sitemaps`,
'coding/web-design':`Web Design`,
'recipes/desserts/almond-cake':`Almond cake`,
'recipes/desserts/date-balls':`Date Balls`,
'recipes/desserts/ginger-snaps':`Ginger snaps`,
'recipes/desserts/rainbow-cookies':`Rainbow Cookies`,
'recipes/desserts/tiramisu':`Tiramisu`,
'recipes/desserts':`Desserts`,
'recipes/meats/chicken-meatballs':`Chicken meatballs`,
'recipes/meats':`Meats`,
'recipes/sides/macaroni-and-cheese-1-pot-version':`One-Pot Macaroni and Cheese Recipe`,
'recipes/sides/mashed-potatoes':`Mashed potatoes`,
'recipes/sides/yeast-rolls':`Yeast Rolls`,
'recipes/sides':`Sides`,
'recipes/want-to-try/beef-stew/beef-stew-20240120-bard':``,
'recipes/want-to-try/beef-stew/beef-stew-20240120-bing':``,
'recipes/want-to-try/beef-stew/beef-stew-20240120-chatgpt':``,
'recipes/want-to-try/crab-cakes/crab-cakes-20240120-bard':``,
'recipes/want-to-try/crab-cakes/crab-cakes-20240120-bing':``,
'recipes/want-to-try/crab-cakes/crab-cakes-20240120-chatgpt':``,
'recipes/want-to-try':`Recipes we want to try`,
'recipes':`Recipes`,
'sitemap':`Sitemap`,
'this-should-not-appear':``,
'upcycling/food-scraps/coffee-grounds':`Reusing Coffee Grounds`,
'upcycling/food-scraps/tea-bags':`Reusing Tea Bags`,
'upcycling/food-scraps':`Creative Reuse of Food Scraps`,
'upcycling/textiles/t-shirts':`Upcycling T-shirts`,
'upcycling/textiles':`Creative Reuse of Textiles`,
'upcycling':`Creative Reuse`,
'':`Welcome  `,
}
